package com.swp08.dpss.mapper.interfaces.survey;

import com.swp08.dpss.dto.requests.survey.QuestionOptionRequest;
import com.swp08.dpss.dto.responses.survey.QuestionOptionDto;
import com.swp08.dpss.entity.survey.QuestionOption;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.util.List;

@Mapper(componentModel = "spring")
public interface QuestionOptionMapper {

    // Map QuestionOption entity to DTO
    @Mapping(target = "id", source = "id")
    @Mapping(target = "content", source = "content")
    @Mapping(target = "correct", source = "correct")
    QuestionOptionDto toDto(QuestionOption entity);
    List<QuestionOptionDto> toDtoList(List<QuestionOption> entities);

    // Map Request DTO to entity (for creating/updating options)
    // Note: 'question' relationship will be set by the service layer
    @Mapping(target = "id", ignore = true) // ID is generated by DB
    @Mapping(target = "question", ignore = true) // Relationship set by service
    QuestionOption toEntity(QuestionOptionRequest dto);
    List<QuestionOption> toEntityList(List<QuestionOptionRequest> dtos);
}