package com.swp08.dpss.mapper.interfaces.survey;

import com.swp08.dpss.dto.requests.survey.AnswerOptionRequest;
import com.swp08.dpss.dto.responses.survey.AnswerOptionDto;
import com.swp08.dpss.entity.survey.AnswerOption;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.util.List;

@Mapper(componentModel = "spring")
public interface QuestionOptionMapper {

    // Map AnswerOption entity to DTO
    @Mapping(target = "id", source = "id")
    @Mapping(target = "content", source = "content")
    @Mapping(target = "correct", source = "correct")
    AnswerOptionDto toDto(AnswerOption entity);
    List<AnswerOptionDto> toDtoList(List<AnswerOption> entities);

    // Map Request DTO to entity (for creating/updating options)
    // Note: 'question' relationship will be set by the service layer
    @Mapping(target = "id", ignore = true) // ID is generated by DB
    @Mapping(target = "question", ignore = true) // Relationship set by service
    AnswerOption toEntity(AnswerOptionRequest dto);
    List<AnswerOption> toEntityList(List<AnswerOptionRequest> dtos);
}