package com.swp08.dpss.mapper.interfaces.survey;

import com.swp08.dpss.dto.responses.survey.SurveyQuestionDto;
import com.swp08.dpss.dto.requests.survey.SurveyQuestionRequest; // Import request DTO
import com.swp08.dpss.entity.survey.SurveyQuestion;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

import java.util.List;

@Mapper(componentModel = "spring", uses = {QuestionOptionMapper.class, SurveyAnswerMapper.class}) // Add QuestionOptionMapper
public interface SurveyQuestionMapper {

    @Mapping(source = "question_id", target = "id")
    @Mapping(source = "question", target = "question")
    @Mapping(source = "type", target = "type")
    // Remove mappings for 'solution' and 'value'
    @Mapping(target = "options", source = "options") // Map the new options list
    @Mapping(source = "survey.id", target = "surveyId")
    SurveyQuestionDto toDto(SurveyQuestion entity);
    List<SurveyQuestionDto> toDtoList(List<SurveyQuestion> entities);

    // New method to map request DTO to entity (for add/update)
    @Mapping(target = "question_id", ignore = true) // ID generated by DB
    @Mapping(target = "survey", ignore = true) // Set by service layer
    @Mapping(target = "answers", ignore = true) // Answers are managed separately
    // Options need to be mapped (from AnswerOptionRequest to AnswerOption)
    @Mapping(target = "options", source = "options")
    SurveyQuestion toEntity(SurveyQuestionRequest dto);

    // Method for updating existing entity from request DTO
    @Mapping(target = "question_id", ignore = true) // Don't update ID
    @Mapping(target = "survey", ignore = true) // Don't update relationship
    @Mapping(target = "answers", ignore = true) // Don't update answers
    // Options will need to be handled carefully in the service (add/remove existing options)
    // For now, just map the simple fields
    @Mapping(target = "options", ignore = true) // Options list might need custom handling in service for updates
    void updateEntityFromDto(SurveyQuestionRequest dto, @MappingTarget SurveyQuestion entity);
}